const TRIAGE_DATA = [
  CATEGORY_FLAVOR,
  CATEGORY_GRAINS,
  CATEGORY_PASTA,
  CATEGORY_SAUCES,
  CATEGORY_MEAT,
  CATEGORY_SEAFOOD,
  CATEGORY_EGGS,
  CATEGORY_VEGETABLES,
  CATEGORY_HEAT_PAN,
  CATEGORY_BAKING,
  CATEGORY_SOUPS,
  CATEGORY_DAIRY,
  CATEGORY_FRYING,
  CATEGORY_RESCUE
];